### ISSUE TITLE
DmxData Buffer doesn't go beyond 15 universes

### ISSUE THREAD

**Issue by Nexyll** [cansik/artnet4j#14]
Hi,

It seems that the input buffer only support universe 0 thru 15, when we try to read data over the fifteenth universe all channel are at 0.

the concerned method is `readDmxData` from the `ArtNetClient` class.

An idea of the cause of this limitation ?

**Comment by cansik** [comment]
The [ArtNetBuffer](https://github.com/cansik/artnet4j/blob/master/src/main/java/ch/bildspur/artnet/ArtNetBuffer.java#L23-L30) is implemented to create a new channel on demand.

It seems that the [OpDMX](https://github.com/cansik/artnet4j/blob/master/src/main/java/ch/bildspur/artnet/packets/ArtDmxPacket.java#L68) parsing is limiting the value to 16 by masking it with `0x0F`. I am not sure at the moment if this is needed or how the ArtNet standard handles this. Because atm in the code, the universe is the lower part of the 8bit subnet number, which means we only have 4bit to represent the universe (which is 16 in decimal).

**Comment by cansik** [comment]
So it seems that we would have to combine the subnet and the universe into one number by shifting them back:

```java
int overSixTeenUniverse = dmxPackage.getSubnetID() << 4 | dmxPackage.getUniverseID();
```

**Comment by Nexyll** [comment]
Thank you for your answer, I had misunderstood the specification, I must have confused net and subnet in the ArtDmx packet description.

The code seems to implement the specification correctly.

|Bit 15|Bits 14-8|Bits 7-4|Bits 3-0|
|---|---|---|---|
|0|Net|Sub-Net|Universe|

Thanks again for your help 😉
